// تعریف همه‌ی منابع قابل مدیریت. هر منبع در پنل مدیر CRUD می‌شود.
// group: content = ویراستار هم می‌تواند؛ admin = فقط مدیر کل. ro = فقط مشاهده/حذف
export const LABELS = {
  slug: 'شناسه انگلیسی (slug)', name: 'نام', title: 'عنوان', description: 'توضیح', kind: 'نوع', est_minutes: 'زمان تقریبی (دقیقه)', level: 'سطح',
  science_note: 'مبنای علمی و محدودیت‌ها', result_note: 'نکته‌ی نتیجه', is_published: 'منتشر شده', sort_order: 'ترتیب', test_id: 'شماره‌ی تست', code: 'کد',
  suggested_majors: 'رشته‌های پیشنهادی (slug با ویرگول)', suggested_jobs: 'مشاغل پیشنهادی (slug)', suggested_skills: 'مهارت‌های پیشنهادی (slug)', next_action: 'اقدام بعدی',
  category_code: 'کد دسته', q_text: 'متن سؤال', weight: 'وزن', is_active: 'فعال', question_id: 'شماره‌ی سؤال', o_text: 'متن گزینه', score: 'امتیاز',
  suitable_for: 'مناسب چه کسانی', key_lessons: 'درس‌های مهم', abilities: 'توانایی‌های لازم', skills: 'مهارت‌ها', universities: 'دانشگاه‌ها', study_path: 'مسیر تحصیلی',
  related_jobs: 'مشاغل مرتبط (slug)', job_market: 'بازار کار', future_skills: 'مهارت‌های آینده', pros: 'مزایا', challenges: 'چالش‌ها', faq: 'سؤالات متداول', similar_majors: 'رشته‌های مشابه (slug)',
  holland_codes: 'کدهای هالند (مثل I,C)', konkur_group: 'گروه کنکور', intro: 'معرفی', duties: 'وظایف', related_majors: 'رشته‌های مرتبط (slug)', entry_path: 'مسیر ورود', education: 'تحصیلات',
  essential_skills: 'مهارت‌های ضروری', tools: 'ابزارها', work_env: 'محیط کار', growth_path: 'مسیر رشد', related_experts: 'افراد متخصص مرتبط', category: 'دسته', how_to_learn: 'روش یادگیری',
  grade: 'پایه', field_name: 'رشته', author: 'نویسنده', publisher: 'ناشر', image_url: 'آدرس تصویر', link_url: 'لینک', summary: 'خلاصه', body: 'متن', published_at: 'تاریخ انتشار',
  user_id: 'شماره‌ی کاربر', provider_type: 'نوع (counselor/professional/mentor/coach)', photo_url: 'آدرس عکس', specialty: 'تخصص', experience: 'تجربه', city: 'شهر', coaching_model: 'مدل کوچینگ',
  coach_types: 'انواع کوچینگ (goal,study,career,path)', background: 'سابقه', documents_note: 'مدارک', tags: 'برچسب‌ها', price: 'قیمت (تومان)', duration_min: 'مدت (دقیقه)', status: 'وضعیت', admin_note: 'یادداشت مدیر',
  provider_id: 'شماره‌ی ارائه‌دهنده', mode: 'روش ارتباط', is_enabled: 'فعال', start_at: 'شروع', end_at: 'پایان', is_booked: 'رزرو شده', weekday: 'روز هفته (0 یکشنبه … 6 شنبه)', start_time: 'ساعت شروع', end_time: 'ساعت پایان', slot_minutes: 'طول هر جلسه',
  coach_type: 'نوع کوچینگ', sessions_count: 'تعداد جلسه', weeks: 'تعداد هفته', coach_id: 'شماره‌ی کوچ (ارائه‌دهنده)', capacity: 'ظرفیت', sessions_desc: 'جلسات', actions_desc: 'اقدامات', rules: 'قوانین', start_date: 'تاریخ شروع', end_date: 'تاریخ پایان',
  percent: 'درصد تخفیف', is_used: 'استفاده شده', expires_at: 'انقضا', placement: 'محل نمایش', media_type: 'نوع رسانه (image/video/embed)', media_url: 'آدرس رسانه', poster_url: 'تصویر پیش‌نمایش ویدیو', starts_at: 'شروع نمایش', ends_at: 'پایان نمایش',
  question: 'سؤال', answer: 'پاسخ', trigger_type: 'نوع محرک', trigger_value: 'مقدار محرک', link: 'لینک', setting_key: 'کلید', setting_value: 'مقدار', group_name: 'گروه', label: 'برچسب', is_public: 'عمومی',
  card_number: 'شماره کارت', card_owner: 'نام صاحب کارت', bank_name: 'بانک', instructions: 'متن پرداخت', min_amount: 'حداقل مبلغ', max_amount: 'حداکثر مبلغ', receipt_required: 'رسید اجباری',
  provider_name: 'نام سرویس', base_url: 'آدرس API', model: 'مدل', system_prompt: 'دستور سیستمی', temperature: 'دما', max_tokens: 'حداکثر توکن', daily_limit: 'سقف پیام روزانه هر کاربر',
  email: 'ایمیل', phone: 'تلفن', role: 'نقش', permissions: 'مجوزها (JSON)', steps: 'مراحل (هر خط: عنوان | توضیح | لینک)', majors: 'رشته‌ها (slug)', jobs: 'مشاغل (slug)',
  id: 'شناسه', created_at: 'تاریخ ایجاد', status_: 'وضعیت',
};

const CONTENT = 'content';
export const RES = {
  tests: { label: 'تست‌ها', group: CONTENT, table: 'tests', title: 'title', search: ['title', 'slug'], order: 'sort_order, id', pub: 'is_published',
    fields: { slug: 's!', title: 't!', description: 'x', kind: 'e:likert|ability', est_minutes: 'i', level: 't', science_note: 'x', result_note: 'x', is_published: 'b', sort_order: 'i' } },
  test_categories: { label: 'دسته‌بندی نتیجه‌ی تست', group: CONTENT, table: 'test_categories', title: 'title', search: ['title', 'code'], order: 'test_id, sort_order, id', filters: ['test_id'],
    fields: { test_id: 'i!', code: 't!', title: 't!', description: 'x', suggested_majors: 't', suggested_jobs: 't', suggested_skills: 't', next_action: 'x', sort_order: 'i' } },
  questions: { label: 'سؤال‌ها', group: CONTENT, table: 'questions', title: 'q_text', search: ['q_text'], order: 'test_id, sort_order, id', filters: ['test_id', 'category_code'],
    fields: { test_id: 'i!', category_code: 't!', q_text: 'x!', level: 't', weight: 'r', sort_order: 'i', is_active: 'b' } },
  options: { label: 'گزینه‌ها و امتیاز', group: CONTENT, table: 'options', title: 'o_text', search: ['o_text'], order: 'question_id, sort_order, id', filters: ['question_id'],
    fields: { question_id: 'i!', o_text: 't!', score: 'r!', sort_order: 'i' } },
  majors: { label: 'رشته‌ها', group: CONTENT, table: 'majors', title: 'name', search: ['name', 'slug'], order: 'sort_order, id', pub: 'is_published',
    fields: { slug: 's!', name: 't!', description: 'x', suitable_for: 'x', key_lessons: 'x', abilities: 'x', skills: 'x', universities: 'x', study_path: 'x', related_jobs: 't', job_market: 'x', future_skills: 'x', pros: 'x', challenges: 'x', faq: 'x', similar_majors: 't', holland_codes: 't', konkur_group: 't', is_published: 'b', sort_order: 'i' } },
  jobs: { label: 'مشاغل', group: CONTENT, table: 'jobs', title: 'name', search: ['name', 'slug'], order: 'sort_order, id', pub: 'is_published',
    fields: { slug: 's!', name: 't!', intro: 'x', duties: 'x', skills: 'x', related_majors: 't', entry_path: 'x', education: 'x', essential_skills: 'x', tools: 'x', work_env: 'x', growth_path: 'x', faq: 'x', related_experts: 'x', holland_codes: 't', is_published: 'b', sort_order: 'i' } },
  skills: { label: 'مهارت‌ها', group: CONTENT, table: 'skills', title: 'name', search: ['name', 'slug'], order: 'sort_order, id', pub: 'is_published',
    fields: { slug: 's!', name: 't!', description: 'x', category: 't', level: 't', how_to_learn: 'x', is_published: 'b', sort_order: 'i' } },
  lessons: { label: 'دروس', group: CONTENT, table: 'lessons', title: 'name', search: ['name', 'slug'], order: 'sort_order, id', pub: 'is_published',
    fields: { slug: 's!', name: 't!', grade: 't', field_name: 't', description: 'x', is_published: 'b', sort_order: 'i' } },
  career_paths: { label: 'مسیرهای شخصی (قالب)', group: CONTENT, table: 'career_paths', title: 'title', search: ['title', 'slug'], order: 'sort_order, id', pub: 'is_published',
    fields: { slug: 's!', title: 't!', description: 'x', holland_codes: 't', majors: 't', jobs: 't', steps: 'X', is_published: 'b', sort_order: 'i' } },
  resources: { label: 'منابع و کتاب‌ها', group: CONTENT, table: 'resources', title: 'title', search: ['title', 'author'], order: 'sort_order, id', pub: 'is_published',
    fields: { title: 't!', author: 't', publisher: 't', category: 't', level: 't', description: 'x', image_url: 'u', link_url: 'u', is_published: 'b', sort_order: 'i' } },
  articles: { label: 'مقالات', group: CONTENT, table: 'articles', title: 'title', search: ['title', 'slug'], order: 'id DESC', pub: 'is_published', heavy: ['body'],
    fields: { slug: 's!', title: 't!', category: 't', summary: 'x', body: 'X', image_url: 'u', author: 't', is_published: 'b', published_at: 'd' } },
  faqs: { label: 'سؤالات متداول', group: CONTENT, table: 'faqs', title: 'question', search: ['question'], order: 'sort_order, id', pub: 'is_active',
    fields: { category: 't', question: 't!', answer: 'x!', sort_order: 'i', is_active: 'b' } },
  banners: { label: 'بنرها و تبلیغات', group: CONTENT, table: 'banners', title: 'title', search: ['title'], order: 'sort_order, id',
    fields: { placement: 't', title: 't', media_type: 'e:image|video|embed', media_url: 'u!', poster_url: 'u', link_url: 'u', is_active: 'b', starts_at: 'd', ends_at: 'd', sort_order: 'i' } },
  smart_suggestions: { label: 'پیشنهادهای هوشمند', group: CONTENT, table: 'smart_suggestions', title: 'title', search: ['title'], order: 'sort_order, id', pub: 'is_active',
    fields: { trigger_type: 'e:always|no_test|no_goal|holland_code|major|job', trigger_value: 't', title: 't!', description: 'x', link: 't', sort_order: 'i', is_active: 'b' } },
  providers: { label: 'مشاوران، کوچ‌ها، منتورها و متخصصان', group: 'admin', table: 'providers', title: 'name', search: ['name', 'specialty', 'city'], order: 'id DESC', filters: ['status', 'provider_type'],
    fields: { user_id: 'i', provider_type: 'e:counselor|professional|mentor|coach', name: 't!', photo_url: 'u', specialty: 't', experience: 't', city: 't', description: 'x', coaching_model: 'x', coach_types: 't', background: 'x', documents_note: 'x', tags: 't', price: 'i', duration_min: 'i', status: 'e:pending|approved|rejected|disabled', admin_note: 'x' } },
  provider_modes: { label: 'روش‌های ارتباط', group: 'admin', table: 'provider_modes', title: 'mode', order: 'provider_id, id', filters: ['provider_id'],
    fields: { provider_id: 'i!', mode: 'e:chat|phone|in_person|video', is_enabled: 'b' } },
  availability_slots: { label: 'زمان‌های آزاد', group: 'admin', table: 'availability_slots', title: 'start_at', order: 'start_at DESC', filters: ['provider_id', 'is_booked'],
    fields: { provider_id: 'i!', start_at: 'd!', end_at: 'd!', is_booked: 'b' } },
  coach_availability: { label: 'الگوی هفتگی زمان آزاد', group: 'admin', table: 'coach_availability', title: 'weekday', order: 'provider_id, weekday', filters: ['provider_id'],
    fields: { provider_id: 'i!', weekday: 'i!', start_time: 't!', end_time: 't!', slot_minutes: 'i' } },
  coaching_packages: { label: 'بسته‌های کوچینگ', group: 'admin', table: 'coaching_packages', title: 'title', order: 'id',
    fields: { coach_type: 'e:goal|study|career|path', title: 't!', description: 'x', sessions_count: 'i', weeks: 'i', price: 'i', is_active: 'b' } },
  group_coaching_programs: { label: 'کوچینگ گروهی', group: 'admin', table: 'group_coaching_programs', title: 'title', order: 'id DESC',
    fields: { title: 't!', description: 'x', coach_id: 'i', capacity: 'i', weeks: 'i', price: 'i', sessions_desc: 'x', actions_desc: 'x', rules: 'x', start_date: 'd', end_date: 'd', status: 'e:open|closed|running|finished' } },
  coupons: { label: 'کوپن‌های تخفیف', group: 'admin', table: 'coupons', title: 'code', search: ['code'], order: 'id DESC', filters: ['user_id', 'is_used'],
    fields: { code: 't!', user_id: 'i', percent: 'i!', kind: 'e:manual|referral_inviter|referral_invitee', is_used: 'b', expires_at: 'd' } },
  site_settings: { label: 'تنظیمات سایت', group: 'admin', table: 'site_settings', pk: 'setting_key', title: 'setting_key', search: ['setting_key', 'label'], order: 'group_name, setting_key',
    fields: { setting_key: 's!', setting_value: 'X', group_name: 't', label: 't', is_public: 'b' } },
  payment_settings: { label: 'تنظیمات پرداخت (کارت‌به‌کارت)', group: 'admin', table: 'payment_settings', title: 'card_owner', order: 'id', single: true,
    fields: { card_number: 't', card_owner: 't', bank_name: 't', instructions: 'x', rules: 'x', min_amount: 'i', max_amount: 'i', receipt_required: 'b' } },
  ai_settings: { label: 'تنظیمات مشاور AI', group: 'admin', table: 'ai_settings', title: 'provider_name', order: 'id', single: true,
    fields: { is_enabled: 'b', provider_name: 't', base_url: 'u', model: 't', system_prompt: 'X', temperature: 'r', max_tokens: 'i', daily_limit: 'i' } },
  roles: { label: 'نقش‌ها و مجوزها', group: 'admin', table: 'roles', title: 'title', order: 'id', noCreate: false,
    fields: { code: 's!', title: 't!', permissions: 'j' } },
  users: { label: 'کاربران', group: 'admin', table: 'users', title: 'name', search: ['name', 'email'], order: 'id DESC', filters: ['role', 'status'], noCreate: true,
    select: 'id, name, email, phone, role, status, referral_code, referred_by, created_at, last_login_at',
    fields: { name: 't!', phone: 't', role: 'e:admin|editor|student|counselor|professional|mentor|coach', status: 'e:active|blocked' } },
  // فقط‌خواندنی (مشاهده و حذف)
  consultation_requests: { label: 'رزروها و درخواست‌های خدمت', group: 'admin', table: 'consultation_requests', title: 'id', order: 'id DESC', filters: ['status', 'user_id', 'provider_id'], ro: true },
  payments: { label: 'پرداخت‌ها', group: 'admin', table: 'payments', title: 'tracking_code', order: 'id DESC', filters: ['status', 'user_id'], ro: true },
  bookings: { label: 'رزروهای زمان', group: 'admin', table: 'bookings', title: 'id', order: 'id DESC', ro: true },
  test_results: { label: 'نتایج تست‌ها', group: 'admin', table: 'test_results', title: 'id', order: 'id DESC', filters: ['user_id', 'test_id'], ro: true },
  study_plans: { label: 'برنامه‌های مطالعه', group: 'admin', table: 'study_plans', title: 'id', order: 'id DESC', filters: ['user_id'], ro: true },
  exam_plans: { label: 'برنامه‌های کنکور', group: 'admin', table: 'exam_plans', title: 'id', order: 'id DESC', filters: ['user_id'], ro: true },
  goals: { label: 'اهداف کاربران', group: 'admin', table: 'goals', title: 'title', order: 'id DESC', filters: ['user_id', 'status'], ro: true },
  actions: { label: 'اقدام‌های کاربران', group: 'admin', table: 'actions', title: 'title', order: 'id DESC', filters: ['user_id', 'goal_id'], ro: true },
  coaching_programs: { label: 'برنامه‌های کوچینگ', group: 'admin', table: 'coaching_programs', title: 'title', order: 'id DESC', filters: ['user_id', 'coach_id', 'status'], ro: true },
  coaching_goals: { label: 'اهداف کوچینگ', group: 'admin', table: 'coaching_goals', title: 'title', order: 'id DESC', filters: ['program_id'], ro: true },
  coaching_actions: { label: 'اقدام‌های کوچینگ', group: 'admin', table: 'coaching_actions', title: 'title', order: 'id DESC', filters: ['program_id'], ro: true },
  coaching_sessions: { label: 'جلسات کوچینگ', group: 'admin', table: 'coaching_sessions', title: 'id', order: 'id DESC', filters: ['program_id', 'coach_id'], ro: true },
  coaching_checkins: { label: 'Check-inها', group: 'admin', table: 'coaching_checkins', title: 'id', order: 'id DESC', filters: ['user_id'], ro: true },
  group_coaching_members: { label: 'اعضای کوچینگ گروهی', group: 'admin', table: 'group_coaching_members', title: 'id', order: 'id DESC', filters: ['program_id'], ro: true },
  referrals: { label: 'دعوت‌ها', group: 'admin', table: 'referrals', title: 'id', order: 'id DESC', ro: true },
  audit_logs: { label: 'گزارش رویدادها (Audit)', group: 'admin', table: 'audit_logs', title: 'action', order: 'id DESC', filters: ['user_id', 'action'], ro: true },
};
export const pkOf = (r) => r.pk || 'id';

// منابع متعلق به کاربر (API «من»)
export const OWN = {
  goals: { table: 'goals', order: 'is_main DESC, id DESC',
    fields: { title: 't!', description: 'x', category: 't', start_date: 'd', end_date: 'd', priority: 'e:low|medium|high', status: 'e:not_started|in_progress|completed|paused', progress: 'i', is_main: 'b' } },
  actions: { table: 'actions', order: 'id DESC', filters: ['goal_id'],
    fields: { goal_id: 'i', title: 't!', status: 'e:pending|done|not_done|partial', fail_reason: 't', due_date: 'd' } },
  checkins: { table: 'coaching_checkins', order: 'id DESC',
    fields: { program_id: 'i', done_today: 'x', went_well: 'x', was_hard: 'x', obstacles: 'x', next_week: 'x' } },
};
